# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editorUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(934, 718)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/image/win.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 934, 26))
        self.menubar.setObjectName("menubar")
        self.filemenu = QtWidgets.QMenu(self.menubar)
        self.filemenu.setObjectName("filemenu")
        self.editmenu = QtWidgets.QMenu(self.menubar)
        self.editmenu.setObjectName("editmenu")
        self.helpmenu = QtWidgets.QMenu(self.menubar)
        self.helpmenu.setObjectName("helpmenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.toolBar.setFont(font)
        self.toolBar.setAcceptDrops(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.filenew = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/new/image/new.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filenew.setIcon(icon1)
        self.filenew.setObjectName("filenew")
        self.fileopen = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/new/image/open.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileopen.setIcon(icon2)
        self.fileopen.setObjectName("fileopen")
        self.filesave = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/new/image/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filesave.setIcon(icon3)
        self.filesave.setObjectName("filesave")
        self.othersave = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/new/image/save_as.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.othersave.setIcon(icon4)
        self.othersave.setObjectName("othersave")
        self.copy_action = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/new/image/copy.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copy_action.setIcon(icon5)
        self.copy_action.setObjectName("copy_action")
        self.paste_action = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/new/image/paste.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.paste_action.setIcon(icon6)
        self.paste_action.setObjectName("paste_action")
        self.font_action = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/new/image/font.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.font_action.setIcon(icon7)
        self.font_action.setObjectName("font_action")
        self.color_action = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/new/image/color.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.color_action.setIcon(icon8)
        self.color_action.setObjectName("color_action")
        self.aboutQt_action = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/new/image/about.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutQt_action.setIcon(icon9)
        self.aboutQt_action.setObjectName("aboutQt_action")
        self.close_action = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/new/image/close.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_action.setIcon(icon10)
        self.close_action.setObjectName("close_action")
        self.cut_action = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/new/image/cut.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cut_action.setIcon(icon11)
        self.cut_action.setObjectName("cut_action")
        self.filemenu.addAction(self.filenew)
        self.filemenu.addSeparator()
        self.filemenu.addAction(self.fileopen)
        self.filemenu.addSeparator()
        self.filemenu.addAction(self.filesave)
        self.filemenu.addSeparator()
        self.filemenu.addAction(self.othersave)
        self.filemenu.addSeparator()
        self.filemenu.addAction(self.close_action)
        self.editmenu.addAction(self.copy_action)
        self.editmenu.addSeparator()
        self.editmenu.addAction(self.cut_action)
        self.editmenu.addSeparator()
        self.editmenu.addAction(self.paste_action)
        self.editmenu.addSeparator()
        self.editmenu.addAction(self.font_action)
        self.editmenu.addSeparator()
        self.editmenu.addAction(self.color_action)
        self.helpmenu.addAction(self.aboutQt_action)
        self.menubar.addAction(self.filemenu.menuAction())
        self.menubar.addAction(self.editmenu.menuAction())
        self.menubar.addAction(self.helpmenu.menuAction())
        self.toolBar.addAction(self.filenew)
        self.toolBar.addAction(self.fileopen)
        self.toolBar.addAction(self.filesave)
        self.toolBar.addAction(self.othersave)
        self.toolBar_2.addAction(self.copy_action)
        self.toolBar_2.addAction(self.cut_action)
        self.toolBar_2.addAction(self.paste_action)
        self.toolBar_2.addAction(self.font_action)
        self.toolBar_2.addAction(self.color_action)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Editor"))
        self.filemenu.setTitle(_translate("MainWindow", "文件"))
        self.editmenu.setTitle(_translate("MainWindow", "编辑"))
        self.helpmenu.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.filenew.setText(_translate("MainWindow", "新建"))
        self.filenew.setToolTip(_translate("MainWindow", "新建 Ctrl+N"))
        self.filenew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.fileopen.setText(_translate("MainWindow", "打开"))
        self.fileopen.setToolTip(_translate("MainWindow", "打开 Ctrl+O"))
        self.fileopen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.filesave.setText(_translate("MainWindow", "保存"))
        self.filesave.setToolTip(_translate("MainWindow", "保存 Ctrl+S"))
        self.filesave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.othersave.setText(_translate("MainWindow", "另存为"))
        self.othersave.setToolTip(_translate("MainWindow", "另存为 Ctrl+Shift+S"))
        self.othersave.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.copy_action.setText(_translate("MainWindow", "复制"))
        self.copy_action.setToolTip(_translate("MainWindow", "复制 Ctrl+C"))
        self.copy_action.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.paste_action.setText(_translate("MainWindow", "粘贴"))
        self.paste_action.setToolTip(_translate("MainWindow", "粘贴 Ctrl+V"))
        self.paste_action.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.font_action.setText(_translate("MainWindow", "字体"))
        self.font_action.setToolTip(_translate("MainWindow", "字体 Ctrl+Shift+F"))
        self.font_action.setShortcut(_translate("MainWindow", "Ctrl+Shift+F"))
        self.color_action.setText(_translate("MainWindow", "颜色"))
        self.color_action.setToolTip(_translate("MainWindow", "颜色 Ctrl+Shift+C"))
        self.color_action.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.aboutQt_action.setText(_translate("MainWindow", "关于Qt"))
        self.aboutQt_action.setToolTip(_translate("MainWindow", "关于Qt Ctrl+Q"))
        self.aboutQt_action.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.close_action.setText(_translate("MainWindow", "关闭"))
        self.close_action.setToolTip(_translate("MainWindow", "关闭 Ctrl+E"))
        self.close_action.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.cut_action.setText(_translate("MainWindow", "剪切"))
        self.cut_action.setToolTip(_translate("MainWindow", "剪切 Ctrl+X"))
        self.cut_action.setShortcut(_translate("MainWindow", "Ctrl+X"))

import res_rc
